version: "3"

services:
  kafka_monitor:
    build:
      context: ./kafka-monitor
    depends_on:
      - kafka
      - redis
    restart: always

  redis_monitor:
    build:
      context: ./redis-monitor
    depends_on:
      - kafka
      - redis
      - zookeeper
    restart: always

  crawler:
    build:
      context: ./crawler
    depends_on:
      - kafka
      - redis
      - zookeeper
    restart: always

  rest:
    image: istresearch/scrapy-cluster:rest-1.2.1
    depends_on:
      - kafka
      - redis
    restart: always
    ports:
      - "5343:5343"

  redis:
    image: redis
    ports:
      - "6379"
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always

  # Convenient way to start key services only
  # Start with: docker-compose up dev
  dev:
    image: alpine # This image doesn't run anything, but allows us to have links
    links:
      - zookeeper
      - kafka
      - redis
      - kafka_monitor
      - redis_monitor
      - crawler
      - rest

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
